#!/bin/bash

set -e

INISO="$1"
KSFILE="$2"
OUTISO="$3"
WRKDIR="$(mktemp -d)"

if [[ $# -ne 3 ]]; then
  echo "$0 <input iso> <kickstart> <output iso>"
  exit 1
fi

VOLNAME=$(isoinfo -d -i $INISO | sed -n 's/Volume id: *\(.\)/\1/p')
KSINS="ks=hd:LABEL=${VOLNAME// /\\\x20}:/isolinux/ks.cfg"

mount -o loop $INISO /mnt

shopt -s dotglob
cp -aRf /mnt/* $WRKDIR/
umount /mnt

chmod 644 $WRKDIR/images/efiboot.img

mount -o loop $WRKDIR/images/efiboot.img /mnt

perl -pi -e "s;quiet;$KSINS;" /mnt/EFI/BOOT/grub.cfg
umount /mnt

chmod 444 $WRKDIR/images/efiboot.img

perl -pi -e "s;quiet;$KSINS;" $WRKDIR/isolinux/isolinux.cfg
perl -pi -e "s;quiet;$KSINS;" $WRKDIR/EFI/BOOT/grub.cfg
cp $KSFILE $WRKDIR/isolinux/ks.cfg

genisoimage \
  -V "$VOLNAME" \
  -A "$VOLNAME" \
  -o "$OUTISO" \
  -joliet-long \
  -b isolinux/isolinux.bin \
  -c isolinux/boot.cat \
  -no-emul-boot \
  -boot-load-size 4 \
  -boot-info-table \
  -eltorito-alt-boot -e images/efiboot.img \
  -no-emul-boot \
  -R -J -v -T \
  $WRKDIR

sudo isohybrid --uefi "$OUTISO"
rm -rf "$WRKDIR"
